import tseslint from 'typescript-eslint';

export default tseslint.config(
  // src/vendor/throttler.js is generated by scripts/bundle-throttler.mjs at build time (gitignored).
  { ignores: ['dist/**', 'src/vendor/*.js'] },
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      // Off: NestJS constructor injection needs runtime class imports; this rule would rewrite them to
      // `import type` and silently erase the decorator metadata Nest depends on.
      '@typescript-eslint/consistent-type-imports': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
);
